### ISSUE TITLE
Communication/collaboration channels

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/meta#8]
Presently this project has no official communication channels besides GitHub Issues (although I maintain a mostly broadcast-only Twitter account at https://twitter.com/RustCryptoOrg)

Should we consider designating some communication channels and adding them to project documentation? Perhaps we could piggyback off the existing Rust Discord or Zulip chats.

**Comment by newpavlov** [comment]
Sounds good! Personally I would prefer to use Zulip or Matrix instead of Discord.

What do you mean by "project documentation"? Something like adding badges to READMEs sounds good, but I don't think it will be correct to add such links to crate docs. We also could create a landing page based on GitHub Pages, add `homepage` field to Cargo.toml and link such resources there.

**Comment by tarcieri** [comment]
> Something like adding badges to READMEs sounds good

Yes, that.

**Comment by tarcieri** [comment]
I created a Zulip: https://rustcrypto.zulipchat.com/

@newpavlov if you join, I can add you as an admin

**Comment by newpavlov** [comment]
Great! I've signed up.
